try {
    let a = 4 + spam*3;
  } catch (error) {
    console.log("There was an error:", error);
  }
  console.log("Following code....");